name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
      - run: npm ci
      - run: npm run ci
      - run: npm run test:package-init

  commitlint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
      - run: npm ci
      - env:
          COMMITLINT_FROM: ${{ github.event.pull_request.base.sha }}
          COMMITLINT_TO: ${{ github.event.pull_request.head.sha }}
        run: npx commitlint --from "$COMMITLINT_FROM" --to "$COMMITLINT_TO" --verbose
